######################## default configuration ####################
baseURL = "https://devopshive.net/"
title = "DevOps Hive"
theme = "bigspring-light"
# post pagination
paginate = 3
# post excerpt
summaryLength = 15
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "G-9RYYHSXPQN" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true

[params.variables]
primary_color = "#f39200"
