############################# English ############################
[en]
languageName = "En"
title = "DevOps Hive"
contentDir = "content/english" # content/english
weight = 1
########### footer content ##########
# footer_menu_left = "Company"
footer_menu_middle = "The Hive"
footer_menu_right = "Support"
footer_content = "DevOps Transformation gate for enterprise and open-source community"
# copyright
copyright = "Design By [Themefisher](https://themefisher.com/) Develop By [Gethugothemes](https://gethugothemes.com/)"
