# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Services"
url = "/#services"
weight = 2

[[main]]
name = "Community"
url = "/#community"
weight = 3

[[main]]
name = "Career Roadmap"
url = "/#career-roadmap"
weight = 4

# [[main]]
# name = "FAQ"
# url = "faq/"
# weight = 4

# # footer menu left
# [[footer_left]]
# name = "About Us"
# url = "#"

# [[footer_left]]
# name = "Quick Start"
# url = "#"

# [[footer_left]]
# name = "Pricing"
# url = "pricing/"


# footer menu middle
# [[footer_middle]]
# name = "About"
# url = "about/"

# [[footer_middle]]
# name = "Community"
# url = "community/"

# [[footer_middle]]
# name = "FAQ"
# url = "faq/"

# footer menu right
# [[footer_right]]
# name = "Privacy Policy"
# url = "privacy-policy/"

# [[footer_right]]
# name = "Terms & Conditions"
# url = "terms-conditions/"

# [[footer_right]]
# name = "FAQ"
# url = "faq/"