#################### default parameters ################################
logo = "images/devops-hive-logo.svg"
logo_width = "200px"
favicon = "images/favicon.png"
# OpenGraph / Twitter Card metadata
description = "DevOps Transformation gate for enterprise and open-source community"
author = "DevOps Hive"
image = "images/devops-hive-icon.png" # this image will be used as fallback if a page has no image of its own
# contact form action
contact_form_action = "https://formspree.io/f/xleyvono" # contact form works with https://formspree.io

# Type of pages to be rendered with a blog view
blogCategoryType = "category"

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation buttons
[navigation_button]
enable = true
label = "Contact Us"
link = "contact/"

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"
  
############################# social site ########################
# themify icon : https://themify.me/themify-icons
[[social]]
title = "linkedin"
icon = "fab fa-linkedin"
link = "https://www.linkedin.com/company/devopshive"

[[social]]
title = "github"
icon = "fab fa-github"
link = "https://github.com/DevOpsHiveHQ"

[[social]]
title = "Telegram"
icon = "fab fa-telegram"
link = "https://t.me/DevOpsHive"
